name: defensa_civil
description: "A new Flutter project."

publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6"

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  http: ^1.2.0
  url_launcher: ^6.2.6
  carousel_slider: ^4.0.0
  provider: ^6.1.2
  image_picker: ^1.0.8
  flutter_map: ^6.1.0
  geolocator: ^11.0.0
  latlong2: ^0.9.1
  youtube_player_flutter: ^8.1.0
  google_maps_flutter: ^2.5.0
  geocoding: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/emergency_preparation.png
    - assets/images/flood_response.jpg
    - assets/images/recovery_support.jpg
    - assets/images/Cristian.jpeg
    - assets/images/Endrik.jpg
    - assets/images/Valerie.jpeg
    - assets/images/Cesar.png
    - assets/images/Loren.jpeg
    - assets/images/imagen1_servicios.jpg
